insert into genre (name) VALUES ('Комедия');
insert into genre (name) VALUES ('Драма');
insert into genre (name) VALUES ('Мультфильм');
insert into genre (name) VALUES ('Триллер');
insert into genre (name) VALUES ('Документальный');
insert into genre (name) VALUES ('Боевик');
insert into rating (name, description) VALUES ('G', 'у фильма нет возрастных ограничений');
insert into rating (name, description) VALUES ('PG', 'детям рекомендуется смотреть фильм с родителями');
insert into rating (name, description) VALUES ('PG-13', 'детям до 13 лет просмотр не желателен');
insert into rating (name, description) VALUES ('R', 'лицам до 17 лет просматривать фильм можно только в присутствии взрослого');
insert into rating (name, description) VALUES ('NC-17', ' лицам до 18 лет просмотр запрещён');
