insert into genre (name) values ('Комедия');
insert into genre (name) values ('Драма');
insert into genre (name) values ('Мультфильм');
insert into genre (name) values ('Триллер');
insert into genre (name) values ('Документальный');
insert into genre (name) values ('Боевик');
insert into rating (name, description) values ('G', 'у фильма нет возрастных ограничений');
insert into rating (name, description) values ('PG', 'детям рекомендуется смотреть фильм с родителями');
insert into rating (name, description) values ('PG-13', 'детям до 13 лет просмотр не желателен');
insert into rating (name, description) values ('R', 'лицам до 17 лет просматривать фильм можно только в присутствии взрослого');
insert into rating (name, description) values ('NC-17', ' лицам до 18 лет просмотр запрещён');
