
create table if not exists users
(
    id int generated by default as identity primary key,
    login  varchar(64) not null,
    email varchar(255),
    name varchar(255),
    birthday timestamp
);


create table if not exists friendship
(
    user_id int not null REFERENCES users(id) ON DELETE CASCADE,
    friend_id int not null REFERENCES users(id) ON DELETE CASCADE,
    is_accepted bool default FALSE,
    UNIQUE (user_id, friend_id)
);

create table if not exists rating
(
    id int generated by default as identity primary key,
    name varchar(64) not null,
    description  varchar(500)
);


create table if not exists film
(
    id int generated by default as identity primary key,
    name varchar(255),
    release_date timestamp,
    description  varchar(64),
    duration int,
    rating_id int REFERENCES rating(id) ON DELETE CASCADE
);

create table if not exists genre
(
    id int generated by default as identity primary key,
    name varchar(255)
);

create table if not exists director
(
    id int generated by default as identity primary key,
    name varchar(255)
);

create table if not exists film_directors
(
    film_id int REFERENCES film(id) ON DELETE CASCADE,
    director_id int REFERENCES director(id) ON DELETE CASCADE
);

create table if not exists film_genre
(
    film_id int REFERENCES film(id) ON DELETE CASCADE,
    genre_id int REFERENCES genre(id) ON DELETE CASCADE
);

create table if not exists likes_film
(
    film_id int REFERENCES film(id) ON DELETE CASCADE,
    user_id int REFERENCES users(id) ON DELETE CASCADE
);

create table if not exists reviews (
    id int generated by default as identity primary key,
    content varchar(255),
    is_positive bool,
    user_id int REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    film_id int REFERENCES film(id) ON DELETE CASCADE NOT NULL
    --user_id int,
    --film_id int
);

create table if not exists review_likes (
    review_id int REFERENCES reviews(id) ON DELETE CASCADE NOT NULL,
    user_id int REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    useful INTEGER
);






